name: Backend Continuous Integration1

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

env:
  PYTHON_VERSION: 3.11

jobs:
  lint:
    name: Backend run lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./udacity-project4/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Folder Structure
        run: |
          echo "Current working directory: $(pwd)"
          echo "Repository contents:"
          ls -R

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run lint
        run: pipenv run flake8 .

  test:
    name: Backend run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./udacity-project4/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Folder Structure
        run: |
          echo "Current working directory: $(pwd)"
          echo "Repository contents:"
          ls -R

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run tests
        run: pipenv run pytest
